-------------------------------------------------------
-- Contents of the BRS_2016_2021_Batting_input table
--    Quick Look at the first 27 rows
-------------------------------------------------------

SELECT * FROM BRS_2016_2021_Batting_input LIMIT 27; 


 Key | Game_Date  |      Team      |     Opponent      | Game_Result | At_Bats | Runs_Scored | Hits | Doubles | Triples | Home_Runs | Runs_Batted_In | Walks | Strikeouts | Hit_By_Pitch | Sacrifice_Hits | Sacrifice_Flies | Reached_On_Error | Grounded_into_Double_Play | Stolen_Bases | Caught_Stealing | Runners_Left_On_Base | Number_of_Players_Used_in_Game | Attendance_in_Tickets_Sold | Game_Length_in_Minutes
-----+------------+----------------+-------------------+-------------+---------+-------------+------+---------+---------+-----------+----------------+-------+------------+--------------+----------------+-----------------+------------------+---------------------------+--------------+-----------------+----------------------+--------------------------------+----------------------------+------------------------
   1 | 2016-04-05 | Boston Red Sox | Cleveland Indians |           1 |      37 |           6 |   11 |       1 |       0 |         2 |              5 |     6 |          8 |            0 |              0 |               0 |                1 |                         1 |            0 |               1 |                   10 |                              9 |                      34493 |                    193
   2 | 2016-04-06 | Boston Red Sox | Cleveland Indians |           0 |      36 |           6 |   10 |       2 |       0 |         3 |              6 |     3 |          7 |            0 |              0 |               1 |                0 |                         0 |            1 |               0 |                    7 |                             11 |                      10298 |                    209
   3 | 2016-04-08 | Boston Red Sox | Toronto Blue Jays |           1 |      38 |           8 |   11 |       4 |       0 |         1 |              8 |     3 |          8 |            0 |              0 |               0 |                1 |                         0 |            0 |               0 |                    6 |                             10 |                      48871 |                    204
   4 | 2016-04-09 | Boston Red Sox | Toronto Blue Jays |           1 |      38 |           8 |   11 |       5 |       1 |         0 |              7 |     4 |         13 |            0 |              0 |               1 |                0 |                         0 |            1 |               0 |                    8 |                              9 |                      47138 |                    168
   5 | 2016-04-10 | Boston Red Sox | Toronto Blue Jays |           0 |      32 |           0 |    7 |       2 |       0 |         0 |              0 |     2 |         11 |            0 |              0 |               0 |                0 |                         1 |            0 |               0 |                    7 |                             10 |                      46158 |                    147
   6 | 2016-04-11 | Boston Red Sox | Baltimore Orioles |           0 |      36 |           7 |   11 |       2 |       0 |         1 |              7 |     4 |          8 |            0 |              0 |               1 |                1 |                         2 |            2 |               0 |                    7 |                             10 |                      37160 |                    206
   7 | 2016-04-12 | Boston Red Sox | Baltimore Orioles |           0 |      35 |           5 |   10 |       4 |       0 |         1 |              4 |     1 |          4 |            2 |              0 |               0 |                0 |                         1 |            0 |               0 |                    6 |                             10 |                      31114 |                    203
   8 | 2016-04-13 | Boston Red Sox | Baltimore Orioles |           1 |      30 |           4 |    8 |       1 |       1 |         0 |              4 |     4 |          7 |            0 |              0 |               0 |                0 |                         1 |            3 |               0 |                    6 |                              9 |                      31011 |                    193
   9 | 2016-04-15 | Boston Red Sox | Toronto Blue Jays |           1 |      32 |           5 |    9 |       3 |       0 |         0 |              5 |     6 |          7 |            0 |              0 |               0 |                1 |                         2 |            1 |               0 |                    9 |                              9 |                      31415 |                    182
  10 | 2016-04-16 | Boston Red Sox | Toronto Blue Jays |           1 |      31 |           4 |    9 |       1 |       0 |         1 |              4 |     2 |          3 |            0 |              0 |               0 |                0 |                         2 |            0 |               0 |                    5 |                              9 |                      36267 |                    163
  11 | 2016-04-17 | Boston Red Sox | Toronto Blue Jays |           0 |      31 |           3 |    4 |       0 |       0 |         1 |              3 |     4 |         10 |            0 |              0 |               0 |                0 |                         0 |            1 |               0 |                    5 |                              9 |                      37217 |                    189
  12 | 2016-04-18 | Boston Red Sox | Toronto Blue Jays |           0 |      32 |           3 |    7 |       4 |       0 |         0 |              3 |     1 |          6 |            0 |              0 |               0 |                0 |                         2 |            0 |               0 |                    3 |                             10 |                      37168 |                    192
  13 | 2016-04-19 | Boston Red Sox | Tampa Bay Rays    |           0 |      30 |           0 |    1 |       0 |       0 |         0 |              0 |     2 |         14 |            0 |              0 |               0 |                0 |                         1 |            0 |               0 |                    2 |                              9 |                      32061 |                    205
  14 | 2016-04-20 | Boston Red Sox | Tampa Bay Rays    |           1 |      34 |           7 |   12 |       3 |       0 |         1 |              7 |     3 |          9 |            1 |              0 |               0 |                0 |                         1 |            2 |               0 |                    7 |                             10 |                      31689 |                    182
  15 | 2016-04-21 | Boston Red Sox | Tampa Bay Rays    |           0 |      42 |           8 |   15 |       7 |       0 |         2 |              7 |     5 |          8 |            0 |              0 |               0 |                0 |                         0 |            2 |               0 |                   12 |                             11 |                      37954 |                    256
  16 | 2016-04-22 | Boston Red Sox | Houston Astros    |           1 |      37 |           6 |   15 |       3 |       2 |         0 |              5 |     1 |          6 |            1 |              0 |               1 |                0 |                         2 |            0 |               0 |                    7 |                             10 |                      26672 |                    208
  17 | 2016-04-23 | Boston Red Sox | Houston Astros    |           0 |      35 |           3 |    9 |       2 |       0 |         0 |              3 |     2 |          9 |            0 |              0 |               1 |                0 |                         0 |            0 |               0 |                    8 |                             10 |                      40232 |                    208
  18 | 2016-04-24 | Boston Red Sox | Houston Astros    |           1 |      49 |           7 |   16 |       3 |       1 |         0 |              6 |     5 |          7 |            0 |              1 |               1 |                1 |                         1 |            2 |               0 |                   13 |                              9 |                      32416 |                    303
  19 | 2016-04-25 | Boston Red Sox | Atlanta Braves    |           1 |      33 |           1 |    6 |       2 |       0 |         1 |              1 |     3 |         11 |            0 |              0 |               0 |                1 |                         0 |            1 |               1 |                    8 |                             13 |                      22735 |                    175
  20 | 2016-04-26 | Boston Red Sox | Atlanta Braves    |           1 |      39 |          11 |   13 |       7 |       1 |         1 |             10 |     3 |          5 |            1 |              0 |               0 |                0 |                         0 |            3 |               0 |                    5 |                             12 |                      23487 |                    172
  21 | 2016-04-27 | Boston Red Sox | Atlanta Braves    |           1 |      34 |           9 |   11 |       3 |       1 |         2 |              9 |     6 |          6 |            0 |              0 |               0 |                0 |                         1 |            1 |               0 |                    7 |                             11 |                      33380 |                    182
  22 | 2016-04-28 | Boston Red Sox | Atlanta Braves    |           0 |      36 |           3 |   10 |       4 |       0 |         0 |              3 |     3 |          9 |            0 |              0 |               0 |                1 |                         1 |            0 |               0 |                    9 |                             11 |                      32232 |                    202
  23 | 2016-04-29 | Boston Red Sox | New York Yankees  |           1 |      33 |           4 |    8 |       1 |       0 |         1 |              4 |     0 |          6 |            0 |              0 |               0 |                1 |                         0 |            0 |               0 |                    5 |                              9 |                      37115 |                    170
  24 | 2016-04-30 | Boston Red Sox | New York Yankees  |           1 |      38 |           8 |   14 |       2 |       2 |         1 |              8 |     6 |          9 |            0 |              0 |               0 |                0 |                         0 |            1 |               0 |                   12 |                             12 |                      37901 |                    210
  25 | 2016-05-01 | Boston Red Sox | New York Yankees  |           1 |      37 |           8 |   14 |       1 |       0 |         2 |              8 |     3 |          4 |            0 |              0 |               0 |                0 |                         0 |            1 |               0 |                    8 |                              9 |                      34279 |                    197
  26 | 2016-05-03 | Boston Red Sox | Chicago White Sox |           0 |      30 |           1 |    4 |       0 |       0 |         1 |              1 |     0 |          6 |            0 |              0 |               0 |                0 |                         1 |            0 |               0 |                    2 |                              9 |                      15025 |                    173
  27 | 2016-05-04 | Boston Red Sox | Chicago White Sox |           1 |      35 |           5 |   11 |       1 |       0 |         1 |              5 |     3 |          7 |            1 |              0 |               0 |                0 |                         3 |            0 |               0 |                    7 |                              9 |                      14383 |                    166

(27 rows)
