----------------------------------------------------
-- Contents of the BRS_2016_2021_WP_input table      
--       Quick Look at the first 27 rows
----------------------------------------------------

SELECT COUNT(*) AS Row_Count FROM BRS_2016_2021_WP_input;


 Row_Count
-----------
       870

(1 row)

SELECT * FROM BRS_2016_2021_WP_input LIMIT 27;


 Key | Game_Date  | Game_Month | Game_Day_of_Week |      Team      |           Opponent            |      Opponent_Division       | Game_Result | Runs_Scored |    Runs_Scored_Metric    | Hits |    Hits_Metric    | Doubles | Triples | Home_Runs | Home_Runs_Metric | Extra_Base_Hits |    Extra_Base_Hits_Metric    | Walks | Strikeouts | Walks_Minus_Strikeouts | Walks_Minus_Strikeouts_Metric
-----+------------+------------+------------------+----------------+-------------------------------+------------------------------+-------------+-------------+--------------------------+------+-------------------+---------+---------+-----------+------------------+-----------------+------------------------------+-------+------------+------------------------+-------------------------------
   1 | 2016-04-05 | April      | Tuesday          | Boston Red Sox | Cleveland Guardians (Indians) | American League (AL) Central |           1 |           6 | Runs_Scored > 5 but <= 9 |   11 | Hits >= 10        |       1 |       0 |         2 | Home_Runs > 1    |               3 | Extra_Base_Hits > 0 but <= 5 |     6 |          8 |                     -2 | Strikeouts > Walks
   2 | 2016-04-06 | April      | Wednesday        | Boston Red Sox | Cleveland Guardians (Indians) | American League (AL) Central |           0 |           6 | Runs_Scored > 5 but <= 9 |   10 | Hits >= 10        |       2 |       0 |         3 | Home_Runs > 1    |               5 | Extra_Base_Hits > 0 but <= 5 |     3 |          7 |                     -4 | Strikeouts > Walks
   3 | 2016-04-08 | April      | Friday           | Boston Red Sox | Toronto Blue Jays             | American League (AL) East    |           1 |           8 | Runs_Scored > 5 but <= 9 |   11 | Hits >= 10        |       4 |       0 |         1 | Home_Runs = 1    |               5 | Extra_Base_Hits > 0 but <= 5 |     3 |          8 |                     -5 | Strikeouts > Walks
   4 | 2016-04-09 | April      | Saturday         | Boston Red Sox | Toronto Blue Jays             | American League (AL) East    |           1 |           8 | Runs_Scored > 5 but <= 9 |   11 | Hits >= 10        |       5 |       1 |         0 | Home_Runs = 0    |               6 | Extra_Base_Hits > 5          |     4 |         13 |                     -9 | Strikeouts > Walks
   5 | 2016-04-10 | April      | Sunday           | Boston Red Sox | Toronto Blue Jays             | American League (AL) East    |           0 |           0 | Runs_Scored <= 1         |    7 | Hits > 3 but <= 9 |       2 |       0 |         0 | Home_Runs = 0    |               2 | Extra_Base_Hits > 0 but <= 5 |     2 |         11 |                     -9 | Strikeouts > Walks
   6 | 2016-04-11 | April      | Monday           | Boston Red Sox | Baltimore Orioles             | American League (AL) East    |           0 |           7 | Runs_Scored > 5 but <= 9 |   11 | Hits >= 10        |       2 |       0 |         1 | Home_Runs = 1    |               3 | Extra_Base_Hits > 0 but <= 5 |     4 |          8 |                     -4 | Strikeouts > Walks
   7 | 2016-04-12 | April      | Tuesday          | Boston Red Sox | Baltimore Orioles             | American League (AL) East    |           0 |           5 | Runs_Scored = 4 or 5     |   10 | Hits >= 10        |       4 |       0 |         1 | Home_Runs = 1    |               5 | Extra_Base_Hits > 0 but <= 5 |     1 |          4 |                     -3 | Strikeouts > Walks
   8 | 2016-04-13 | April      | Wednesday        | Boston Red Sox | Baltimore Orioles             | American League (AL) East    |           1 |           4 | Runs_Scored = 4 or 5     |    8 | Hits > 3 but <= 9 |       1 |       1 |         0 | Home_Runs = 0    |               2 | Extra_Base_Hits > 0 but <= 5 |     4 |          7 |                     -3 | Strikeouts > Walks
   9 | 2016-04-15 | April      | Friday           | Boston Red Sox | Toronto Blue Jays             | American League (AL) East    |           1 |           5 | Runs_Scored = 4 or 5     |    9 | Hits > 3 but <= 9 |       3 |       0 |         0 | Home_Runs = 0    |               3 | Extra_Base_Hits > 0 but <= 5 |     6 |          7 |                     -1 | Strikeouts > Walks
  10 | 2016-04-16 | April      | Saturday         | Boston Red Sox | Toronto Blue Jays             | American League (AL) East    |           1 |           4 | Runs_Scored = 4 or 5     |    9 | Hits > 3 but <= 9 |       1 |       0 |         1 | Home_Runs = 1    |               2 | Extra_Base_Hits > 0 but <= 5 |     2 |          3 |                     -1 | Strikeouts > Walks
  11 | 2016-04-17 | April      | Sunday           | Boston Red Sox | Toronto Blue Jays             | American League (AL) East    |           0 |           3 | Runs_Scored = 2 or 3     |    4 | Hits > 3 but <= 9 |       0 |       0 |         1 | Home_Runs = 1    |               1 | Extra_Base_Hits > 0 but <= 5 |     4 |         10 |                     -6 | Strikeouts > Walks
  12 | 2016-04-18 | April      | Monday           | Boston Red Sox | Toronto Blue Jays             | American League (AL) East    |           0 |           3 | Runs_Scored = 2 or 3     |    7 | Hits > 3 but <= 9 |       4 |       0 |         0 | Home_Runs = 0    |               4 | Extra_Base_Hits > 0 but <= 5 |     1 |          6 |                     -5 | Strikeouts > Walks
  13 | 2016-04-19 | April      | Tuesday          | Boston Red Sox | Tampa Bay Rays                | American League (AL) East    |           0 |           0 | Runs_Scored <= 1         |    1 | Hits <= 3         |       0 |       0 |         0 | Home_Runs = 0    |               0 | Extra_Base_Hits = 0          |     2 |         14 |                    -12 | Strikeouts > Walks
  14 | 2016-04-20 | April      | Wednesday        | Boston Red Sox | Tampa Bay Rays                | American League (AL) East    |           1 |           7 | Runs_Scored > 5 but <= 9 |   12 | Hits >= 10        |       3 |       0 |         1 | Home_Runs = 1    |               4 | Extra_Base_Hits > 0 but <= 5 |     3 |          9 |                     -6 | Strikeouts > Walks
  15 | 2016-04-21 | April      | Thursday         | Boston Red Sox | Tampa Bay Rays                | American League (AL) East    |           0 |           8 | Runs_Scored > 5 but <= 9 |   15 | Hits >= 10        |       7 |       0 |         2 | Home_Runs > 1    |               9 | Extra_Base_Hits > 5          |     5 |          8 |                     -3 | Strikeouts > Walks
  16 | 2016-04-22 | April      | Friday           | Boston Red Sox | Houston Astros                | American League (AL) West    |           1 |           6 | Runs_Scored > 5 but <= 9 |   15 | Hits >= 10        |       3 |       2 |         0 | Home_Runs = 0    |               5 | Extra_Base_Hits > 0 but <= 5 |     1 |          6 |                     -5 | Strikeouts > Walks
  17 | 2016-04-23 | April      | Saturday         | Boston Red Sox | Houston Astros                | American League (AL) West    |           0 |           3 | Runs_Scored = 2 or 3     |    9 | Hits > 3 but <= 9 |       2 |       0 |         0 | Home_Runs = 0    |               2 | Extra_Base_Hits > 0 but <= 5 |     2 |          9 |                     -7 | Strikeouts > Walks
  18 | 2016-04-24 | April      | Sunday           | Boston Red Sox | Houston Astros                | American League (AL) West    |           1 |           7 | Runs_Scored > 5 but <= 9 |   16 | Hits >= 10        |       3 |       1 |         0 | Home_Runs = 0    |               4 | Extra_Base_Hits > 0 but <= 5 |     5 |          7 |                     -2 | Strikeouts > Walks
  19 | 2016-04-25 | April      | Monday           | Boston Red Sox | Atlanta Braves                | National League (NL) East    |           1 |           1 | Runs_Scored <= 1         |    6 | Hits > 3 but <= 9 |       2 |       0 |         1 | Home_Runs = 1    |               3 | Extra_Base_Hits > 0 but <= 5 |     3 |         11 |                     -8 | Strikeouts > Walks
  20 | 2016-04-26 | April      | Tuesday          | Boston Red Sox | Atlanta Braves                | National League (NL) East    |           1 |          11 | Runs_Scored >= 10        |   13 | Hits >= 10        |       7 |       1 |         1 | Home_Runs = 1    |               9 | Extra_Base_Hits > 5          |     3 |          5 |                     -2 | Strikeouts > Walks
  21 | 2016-04-27 | April      | Wednesday        | Boston Red Sox | Atlanta Braves                | National League (NL) East    |           1 |           9 | Runs_Scored > 5 but <= 9 |   11 | Hits >= 10        |       3 |       1 |         2 | Home_Runs > 1    |               6 | Extra_Base_Hits > 5          |     6 |          6 |                      0 | Walks = Strikeouts
  22 | 2016-04-28 | April      | Thursday         | Boston Red Sox | Atlanta Braves                | National League (NL) East    |           0 |           3 | Runs_Scored = 2 or 3     |   10 | Hits >= 10        |       4 |       0 |         0 | Home_Runs = 0    |               4 | Extra_Base_Hits > 0 but <= 5 |     3 |          9 |                     -6 | Strikeouts > Walks
  23 | 2016-04-29 | April      | Friday           | Boston Red Sox | New York Yankees              | American League (AL) East    |           1 |           4 | Runs_Scored = 4 or 5     |    8 | Hits > 3 but <= 9 |       1 |       0 |         1 | Home_Runs = 1    |               2 | Extra_Base_Hits > 0 but <= 5 |     0 |          6 |                     -6 | Strikeouts > Walks
  24 | 2016-04-30 | April      | Saturday         | Boston Red Sox | New York Yankees              | American League (AL) East    |           1 |           8 | Runs_Scored > 5 but <= 9 |   14 | Hits >= 10        |       2 |       2 |         1 | Home_Runs = 1    |               5 | Extra_Base_Hits > 0 but <= 5 |     6 |          9 |                     -3 | Strikeouts > Walks
  25 | 2016-05-01 | May        | Sunday           | Boston Red Sox | New York Yankees              | American League (AL) East    |           1 |           8 | Runs_Scored > 5 but <= 9 |   14 | Hits >= 10        |       1 |       0 |         2 | Home_Runs > 1    |               3 | Extra_Base_Hits > 0 but <= 5 |     3 |          4 |                     -1 | Strikeouts > Walks
  26 | 2016-05-03 | May        | Tuesday          | Boston Red Sox | Chicago White Sox             | American League (AL) Central |           0 |           1 | Runs_Scored <= 1         |    4 | Hits > 3 but <= 9 |       0 |       0 |         1 | Home_Runs = 1    |               1 | Extra_Base_Hits > 0 but <= 5 |     0 |          6 |                     -6 | Strikeouts > Walks
  27 | 2016-05-04 | May        | Wednesday        | Boston Red Sox | Chicago White Sox             | American League (AL) Central |           1 |           5 | Runs_Scored = 4 or 5     |   11 | Hits >= 10        |       1 |       0 |         1 | Home_Runs = 1    |               2 | Extra_Base_Hits > 0 but <= 5 |     3 |          7 |                     -4 | Strikeouts > Walks

(27 rows)